language: python
python:
  - "3.3"
  - "3.4"
# command to install dependencies
install: "pip install -r requirements.txt"
script: ANALYSISDRIVERCONFIG=etc/bcbio_alignment.yaml py.test
branches:
  only:
    - master