language: python
python:
  - "3.4"
  - "3.6"
#Command ran before the install
before_install:
  - "pip install pip --upgrade"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install python-coveralls pytest-cov"
  - "pip install coverage --upgrade"
script: py.test tests -v --cov analysis_driver --cov bin --cov-report term-missing
after_success:
  - coveralls
notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always
env:
  global:
    ANALYSISDRIVERCONFIG=etc/example_analysisdriver.yaml
    EGCGCONFIG=etc/example_analysisdriver.yaml
