language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
#Command ran before the install
before_install:
  - "pip install pip --upgrade"
# command to install dependencies
install: "pip install -r requirements.txt"
script: py.test tests
#branches:
#  only:
#    - master
notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always
env:
  global:
    ANALYSISDRIVERCONFIG=etc/example_analysisdriver.yaml
    EGCGCONFIG=etc/example_analysisdriver.yaml
