
---
testing:
    python: /Users/mwham/workspace/EdGen_Analysis_Driver/Application/envs/3_7_15/bin/python
    bcbio: /scratch/U008/edingen/bin/bcbio/bin/bcbio_nextgen.py
    bcl2fastq: /home/U008/edingen/Applications/bcl2fastq/bcl2fastq_2.17.1.14/bin/bcl2fastq
    fastqc: /scratch/U008/edingen/bin/fastqc/bin/fastqc
    gatk:
        java_home: /home/U008/edingen/Applications/jdk1.7.0_76/
        java_bindir: /home/U008/edingen/Applications/jdk1.7.0_76/bin
        java_root: /home/edingen/Applications/jdk1.7.0_76/

    input_dir: /Users/mwham/workspace/EdGen_Analysis_Driver/input_data
    fastq_dir: /Users/mwham/workspace/EdGen_Analysis_Driver/fastq
    jobs_dir : /Users/mwham/workspace/EdGen_Analysis_Driver/jobs

    transfer_delay: 120
    run_age_cutoff: 5  # in mins

    job_execution: None  # pbs or None
    job_queue: uv2000

    logging:
        format: '%(asctime)s [%(name)s] %(message)s'
        datefmt: '%Y-%b-%d %H:%M:%S'
        handlers:
#           other_handler:
#               level: DEBUG
#               filename: /Users/mwham/workspace/EdGen_Analysis_Driver/Applications/analysis_driver.log
    sample_sheet:
        column_names:
            sample_project: [Sample_Project, SampleProject, Project_Name]
            sample_id: [Sample_ID, SampleID]
            lane: [Lane]
            barcode: [Index, index]
        transformations:
            Project_Name: Sample_Project
    notification:
#        email_notification:
#            mailhost: smtp.staffmail.ed.ac.uk
#            reporter_email: timothee.cezard@ed.ac.uk
#            recipient_emails: [timothee.cezard@ed.ac.uk]
        log_notification: /Users/mwham/workspace/EdGen_Analysis_Driver/analysis_driver_notifications.log
