
---
testing:
    python: /Users/mwham/workspace/EdGen_Analysis_Driver/Application/envs/3_7_15/bin/python
    bcbio: /scratch/U008/edingen/bin/bcbio/bin/bcbio_nextgen.py
    bcl2fastq: /home/U008/edingen/Applications/bcl2fastq/bcl2fastq_2.17.1.14/bin/bcl2fastq
    fastqc: /scratch/U008/edingen/bin/fastqc/bin/fastqc
    gatk:
        java_home: /home/U008/edingen/Applications/jdk1.7.0_76/
        java_bindir: /home/U008/edingen/Applications/jdk1.7.0_76/bin
        java_root: /home/edingen/Applications/jdk1.7.0_76/

    input_dir: /Users/mwham/workspace/EdGen_Analysis_Driver/input_data
    fastq_dir: /Users/mwham/workspace/EdGen_Analysis_Driver/fastq
    jobs_dir : /Users/mwham/workspace/EdGen_Analysis_Driver/jobs

    transfer_delay: 120
    run_age_cutoff: 5  # in mins

    job_execution: None  # pbs or None
    job_queue: uv2000

    logging:
        formatters:
            default_format:
                format: '%(asctime)s [%(name)s] %(message)s'
        handlers:
            stdout:
                level: INFO
                class: logging.StreamHandler
                formatter: default_format
                stream: ext://sys.stdout
#           other_handler:
#               level: DEBUG
#               class: logging.FileHandler
#               formatter: default_format
#               filename: /Users/mwham/workspace/EdGen_Analysis_Driver/Applications/analysis_driver.log

#        loggers:
#            default_logger:
#                handlers:
#                    - stdout
#                level: INFO
#                propagate: False
