__author__ = 'mwham'
import os.path
from logging import getLogger
from analysis_driver.config import default as cfg


logger = getLogger(__name__)


def bcl2fastq(mask, input_dir, fastq_path):
    """
    Write a bcl2fastq command
    :param str mask: A mask to use, as generated by reader.RunInfo
    :param input_dir: Path to the input dir containing the bcl files
    :param fastq_path: Path to the dir in which to send generated .fastqs
    """
    # TODO: make bcl2fastq executable configurable
    cmd = 'bcl2fastq -l INFO --runfolder-dir %s --output-dir %s --sample-sheet %s --use-bases-mask %s' % (
        input_dir, fastq_path, os.path.join(input_dir, 'SampleSheet.csv'), mask
    )
    logger.info('Writing command: ' + cmd)
    return cmd


def fastqc(fastq):
    """
    :param str fastq: An input fastq file
    """
    cmd = 'fastqc --nogroup -q ' + fastq
    logger.info('Writing: ' + cmd)
    return cmd


def bcbio_java_paths():
    cmds = []
    logger.info('Writing bcbio command')

    cmds.append('export JAVA_HOME=' + cfg['gatk']['java_home'])
    cmds.append('export JAVA_BINDIR=' + cfg['gatk']['java_bindir'])
    cmds.append('export JAVA_ROOT=' + cfg['gatk']['java_root'] + '\n')

    return cmds


def bcbio(run_yaml, workdir, cores=16):
    cmd = ('%s %s -n %s --workdir %s' % (cfg['bcbio'], run_yaml, cores, workdir))
    logger.info('Writing: ' + cmd)
    return cmd
